packages:
  - patchnotes-web
  - patchnotes-email
injectWorkspacePackages: true
catalog:
  typescript: ~6.0.3
  react: ^19.2.8
  "@types/react": ^19.2.18
  "@types/node": 22.x
  tailwindcss: ^4.2.2
  vitest: ^4.1.9
onlyBuiltDependencies:
  - esbuild
  - msw
