packages:
  - patchnotes-web
  - patchnotes-email
injectWorkspacePackages: true
catalog:
  "@typescript/native-preview": latest
  typescript: ~6.0.2
  react: ^19.2.5
  "@types/react": ^19.2.14
  "@types/node": 22.x
  tailwindcss: ^4.2.2
  vitest: ^4.1.5
onlyBuiltDependencies:
  - esbuild
  - msw
