/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SubscriptionSuccessRouteImport } from './routes/subscription-success'
import { Route as SubscriptionCanceledRouteImport } from './routes/subscription-canceled'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticateRouteImport } from './routes/authenticate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReleasesReleaseIdRouteImport } from './routes/releases.$releaseId'
import { Route as PackagesOwnerRouteImport } from './routes/packages.$owner'
import { Route as AdminResetRouteImport } from './routes/admin_.reset'
import { Route as AdminEmailsRouteImport } from './routes/admin_.emails'
import { Route as PackagesOwnerIndexRouteImport } from './routes/packages.$owner.index'
import { Route as PackagesOwnerRepoRouteImport } from './routes/packages.$owner.$repo'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionSuccessRoute = SubscriptionSuccessRouteImport.update({
  id: '/subscription-success',
  path: '/subscription-success',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionCanceledRoute = SubscriptionCanceledRouteImport.update({
  id: '/subscription-canceled',
  path: '/subscription-canceled',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticateRoute = AuthenticateRouteImport.update({
  id: '/authenticate',
  path: '/authenticate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesReleaseIdRoute = ReleasesReleaseIdRouteImport.update({
  id: '/releases/$releaseId',
  path: '/releases/$releaseId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/releases.$releaseId.lazy').then((d) => d.Route),
)
const PackagesOwnerRoute = PackagesOwnerRouteImport.update({
  id: '/packages/$owner',
  path: '/packages/$owner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetRoute = AdminResetRouteImport.update({
  id: '/admin_/reset',
  path: '/admin/reset',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin_.reset.lazy').then((d) => d.Route))
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/admin_/emails',
  path: '/admin/emails',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin_.emails.lazy').then((d) => d.Route))
const PackagesOwnerIndexRoute = PackagesOwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackagesOwnerRoute,
} as any)
const PackagesOwnerRepoRoute = PackagesOwnerRepoRouteImport.update({
  id: '/$repo',
  path: '/$repo',
  getParentRoute: () => PackagesOwnerRoute,
} as any).lazy(() =>
  import('./routes/packages.$owner.$repo.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/authenticate': typeof AuthenticateRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/subscription-canceled': typeof SubscriptionCanceledRoute
  '/subscription-success': typeof SubscriptionSuccessRoute
  '/watchlist': typeof WatchlistRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/reset': typeof AdminResetRoute
  '/packages/$owner': typeof PackagesOwnerRouteWithChildren
  '/releases/$releaseId': typeof ReleasesReleaseIdRoute
  '/packages/$owner/$repo': typeof PackagesOwnerRepoRoute
  '/packages/$owner/': typeof PackagesOwnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/authenticate': typeof AuthenticateRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/subscription-canceled': typeof SubscriptionCanceledRoute
  '/subscription-success': typeof SubscriptionSuccessRoute
  '/watchlist': typeof WatchlistRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/reset': typeof AdminResetRoute
  '/releases/$releaseId': typeof ReleasesReleaseIdRoute
  '/packages/$owner/$repo': typeof PackagesOwnerRepoRoute
  '/packages/$owner': typeof PackagesOwnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/authenticate': typeof AuthenticateRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/subscription-canceled': typeof SubscriptionCanceledRoute
  '/subscription-success': typeof SubscriptionSuccessRoute
  '/watchlist': typeof WatchlistRoute
  '/admin_/emails': typeof AdminEmailsRoute
  '/admin_/reset': typeof AdminResetRoute
  '/packages/$owner': typeof PackagesOwnerRouteWithChildren
  '/releases/$releaseId': typeof ReleasesReleaseIdRoute
  '/packages/$owner/$repo': typeof PackagesOwnerRepoRoute
  '/packages/$owner/': typeof PackagesOwnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/authenticate'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/subscription-canceled'
    | '/subscription-success'
    | '/watchlist'
    | '/admin/emails'
    | '/admin/reset'
    | '/packages/$owner'
    | '/releases/$releaseId'
    | '/packages/$owner/$repo'
    | '/packages/$owner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/authenticate'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/subscription-canceled'
    | '/subscription-success'
    | '/watchlist'
    | '/admin/emails'
    | '/admin/reset'
    | '/releases/$releaseId'
    | '/packages/$owner/$repo'
    | '/packages/$owner'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/authenticate'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/subscription-canceled'
    | '/subscription-success'
    | '/watchlist'
    | '/admin_/emails'
    | '/admin_/reset'
    | '/packages/$owner'
    | '/releases/$releaseId'
    | '/packages/$owner/$repo'
    | '/packages/$owner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthenticateRoute: typeof AuthenticateRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionCanceledRoute: typeof SubscriptionCanceledRoute
  SubscriptionSuccessRoute: typeof SubscriptionSuccessRoute
  WatchlistRoute: typeof WatchlistRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminResetRoute: typeof AdminResetRoute
  PackagesOwnerRoute: typeof PackagesOwnerRouteWithChildren
  ReleasesReleaseIdRoute: typeof ReleasesReleaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription-success': {
      id: '/subscription-success'
      path: '/subscription-success'
      fullPath: '/subscription-success'
      preLoaderRoute: typeof SubscriptionSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription-canceled': {
      id: '/subscription-canceled'
      path: '/subscription-canceled'
      fullPath: '/subscription-canceled'
      preLoaderRoute: typeof SubscriptionCanceledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticate': {
      id: '/authenticate'
      path: '/authenticate'
      fullPath: '/authenticate'
      preLoaderRoute: typeof AuthenticateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/$releaseId': {
      id: '/releases/$releaseId'
      path: '/releases/$releaseId'
      fullPath: '/releases/$releaseId'
      preLoaderRoute: typeof ReleasesReleaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$owner': {
      id: '/packages/$owner'
      path: '/packages/$owner'
      fullPath: '/packages/$owner'
      preLoaderRoute: typeof PackagesOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/reset': {
      id: '/admin_/reset'
      path: '/admin/reset'
      fullPath: '/admin/reset'
      preLoaderRoute: typeof AdminResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/emails': {
      id: '/admin_/emails'
      path: '/admin/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$owner/': {
      id: '/packages/$owner/'
      path: '/'
      fullPath: '/packages/$owner/'
      preLoaderRoute: typeof PackagesOwnerIndexRouteImport
      parentRoute: typeof PackagesOwnerRoute
    }
    '/packages/$owner/$repo': {
      id: '/packages/$owner/$repo'
      path: '/$repo'
      fullPath: '/packages/$owner/$repo'
      preLoaderRoute: typeof PackagesOwnerRepoRouteImport
      parentRoute: typeof PackagesOwnerRoute
    }
  }
}

interface PackagesOwnerRouteChildren {
  PackagesOwnerRepoRoute: typeof PackagesOwnerRepoRoute
  PackagesOwnerIndexRoute: typeof PackagesOwnerIndexRoute
}

const PackagesOwnerRouteChildren: PackagesOwnerRouteChildren = {
  PackagesOwnerRepoRoute: PackagesOwnerRepoRoute,
  PackagesOwnerIndexRoute: PackagesOwnerIndexRoute,
}

const PackagesOwnerRouteWithChildren = PackagesOwnerRoute._addFileChildren(
  PackagesOwnerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthenticateRoute: AuthenticateRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionCanceledRoute: SubscriptionCanceledRoute,
  SubscriptionSuccessRoute: SubscriptionSuccessRoute,
  WatchlistRoute: WatchlistRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminResetRoute: AdminResetRoute,
  PackagesOwnerRoute: PackagesOwnerRouteWithChildren,
  ReleasesReleaseIdRoute: ReleasesReleaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
